export interface FocusAreaCategory {
  id: string;
  label: string;
  description: string;
  keywords: string[];
}

export const FOCUS_AREA_CATEGORIES: FocusAreaCategory[] = [
  {
    id: "pacing",
    label: "Pacing",
    description: "Rhythm, tempo, and flow of the narrative",
    keywords: ["pacing", "pace", "rhythm", "tempo", "rushed", "slow", "drag", "momentum", "flow"],
  },
  {
    id: "dialogue",
    label: "Dialogue",
    description: "Character speech, conversation, and voice",
    keywords: [
      "dialogue",
      "dialog",
      "conversation",
      "speech",
      "stilted",
      "banter",
      "spoken",
      "exchanges",
    ],
  },
  {
    id: "show-dont-tell",
    label: "Show Don't Tell",
    description: "Using action and detail instead of exposition",
    keywords: ["show", "tell", "showing", "telling", "exposition", "demonstrate", "illustrate"],
  },
  {
    id: "character",
    label: "Character Development",
    description: "Depth, motivation, and believability of characters",
    keywords: [
      "character",
      "motivation",
      "depth",
      "arc",
      "flat",
      "dimensional",
      "believab",
      "protagonist",
      "antagonist",
      "backstory",
    ],
  },
  {
    id: "imagery",
    label: "Imagery & Description",
    description: "Sensory details, setting, and vivid language",
    keywords: [
      "imagery",
      "sensory",
      "description",
      "vivid",
      "detail",
      "setting",
      "visual",
      "senses",
      "atmosphere",
      "evocative",
    ],
  },
  {
    id: "tension",
    label: "Tension & Conflict",
    description: "Stakes, suspense, and narrative drive",
    keywords: [
      "tension",
      "conflict",
      "stakes",
      "suspense",
      "drama",
      "urgency",
      "threat",
      "danger",
      "anticipation",
    ],
  },
  {
    id: "structure",
    label: "Structure",
    description: "Story organization, transitions, and arc",
    keywords: [
      "structure",
      "organization",
      "transition",
      "arc",
      "beginning",
      "middle",
      "end",
      "plot",
      "resolution",
      "conclusion",
    ],
  },
  {
    id: "voice",
    label: "Voice & Tone",
    description: "Narrative voice, consistency of tone",
    keywords: [
      "voice",
      "tone",
      "style",
      "consistency",
      "narrative",
      "perspective",
      "pov",
      "point of view",
      "narrator",
    ],
  },
  {
    id: "clarity",
    label: "Clarity & Precision",
    description: "Clear prose, word choice, and conciseness",
    keywords: [
      "clarity",
      "clear",
      "concise",
      "wordy",
      "verbose",
      "precise",
      "word choice",
      "diction",
      "tighten",
      "tighter",
      "trim",
    ],
  },
  {
    id: "emotion",
    label: "Emotional Impact",
    description: "Evoking feelings, reader connection",
    keywords: [
      "emotion",
      "emotional",
      "feeling",
      "empathy",
      "connection",
      "resonate",
      "impact",
      "moving",
      "heartfelt",
    ],
  },
  {
    id: "grammar",
    label: "Grammar & Mechanics",
    description: "Sentence structure, punctuation, and correctness",
    keywords: [
      "grammar",
      "punctuation",
      "sentence",
      "syntax",
      "tense",
      "comma",
      "fragment",
      "run-on",
      "spelling",
      "mechanics",
    ],
  },
  {
    id: "general",
    label: "General Craft",
    description: "Overall writing craft and technique",
    keywords: [],
  },
];
